### ISSUE TITLE
UI Error - responsiveness 

### ISSUE THREAD

**Issue by gssakash** [gravitl/netmaker-ui#252]
I've recently noticed that the Footer of the website isn't responsive enough on mobile.

Here's a screenshot of the error - 
![Screenshot_2023-01-09-22-52-38-00_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/52027687/211369447-5a45e570-009f-46e5-bd1f-d319e3ed4579.jpg)

**Comment by Aceix** [comment]
Thanks for spotting. Will check with the team

**Comment by gssakash** [comment]
I could try and fix this as well. Let me know if you would like my help

**Comment by Aceix** [comment]
Fixed now. Thanks for offering
