### ISSUE TITLE
v0.9.0: chosen network is not remembered

### ISSUE THREAD

**Issue by pete1019** [gravitl/netmaker-ui#40]
0.9.0 is nice. Thanks!
But on v0.9.0 the chosen network is not remembered.
Meaning: if you chose a network and then click Nodes, Access Keys, Ext. Clients, DNS in the main menu you will alsways need to choose the network again.

And i have opened another "issue": a search would be nice. Very handy if you have many networks, nodes and so on...

Thanks a lot!

**Comment by 0xdcarns** [comment]
working on it

**Comment by 0xdcarns** [comment]
added in 0.9.1
