### ISSUE TITLE
parameter error with allowedips.

### ISSUE THREAD

**Issue by oycol** [gravitl/netmaker-ui#41]
the allowedips should  list rather  string.

**Comment by pete1019** [comment]
Please give more detail how to reproduce. Thanks

**Comment by oycol** [comment]
![image](https://user-images.githubusercontent.com/23732968/142639996-2dd9a944-a37a-4eac-817f-c05436d06217.png)
 this request is failed, but change it to list, it does well.

**Comment by oycol** [comment]
this func may not run as expected (netmaker-ui/src/Components/Views/NodeDetails.js )，I don't  have  npm env, so , I can't verify. Otherwise, nodeData may have a problem. 
![image](https://user-images.githubusercontent.com/23732968/142703834-75e21674-67f7-4163-8545-3776e6bacfa2.png)

**Comment by 0xdcarns** [comment]
bugfixed in v0.9.0 image, and also in v0.9.1
