### ISSUE TITLE
web session timeout not properly handled

### ISSUE THREAD

**Issue by a1ad** [gravitl/netmaker-ui#51]
After the session timeout it's still possible to can navigate all the different menus (even the keys) except the nodes, the nodes list is empty.
You need to manually reload the webpage to be redirected to the login page.

The redirect needs to happen automatically after the session timeout or when clicking on one of the UI buttons.

**Comment by 0xdcarns** [comment]
I believe this was implemented in v0.9.1, if you want to confirm and we can close this issue

**Comment by a1ad** [comment]
Yes it looks ok now.

**Comment by a1ad** [comment]
Tested it a bit more, definitely solved!
